"""
Train Logistic Regression model for P_solve(u,p) prediction.
Uses synthetic submission data generated by generate_synthetic.py.
"""

import os
import sys
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    roc_auc_score, accuracy_score, classification_report,
    brier_score_loss
)
import joblib

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
MODEL_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "models")

FEATURE_COLS = [
    "user_global_accuracy",
    "user_topic_accuracy",
    "difficulty_gap",
    "difficulty_score",
    "user_total_solved_log",
    "user_recent_accuracy",
    "topic_familiarity",
    "attempt_count",
]
LABEL_COL = "solved"


def load_data():
    csv_path = os.path.join(DATA_DIR, "synthetic_submissions.csv")
    if not os.path.exists(csv_path):
        print(f"Error: {csv_path} not found. Run data/generate_synthetic.py first.")
        sys.exit(1)
    df = pd.read_csv(csv_path)
    print(f"Loaded {len(df)} rows from {csv_path}")
    return df


def train_model(df):
    X = df[FEATURE_COLS].values
    y = df[LABEL_COL].values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    print(f"Train: {len(X_train)}, Test: {len(X_test)}")
    print(f"Label distribution — Train: {y_train.mean():.3f}, Test: {y_test.mean():.3f}")

    # Standardize features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Train logistic regression
    model = LogisticRegression(
        max_iter=1000,
        solver="lbfgs",
        C=1.0,
        random_state=42,
    )
    model.fit(X_train_scaled, y_train)

    # Evaluate
    y_pred_proba = model.predict_proba(X_test_scaled)[:, 1]
    y_pred = model.predict(X_test_scaled)

    auc_roc = roc_auc_score(y_test, y_pred_proba)
    acc = accuracy_score(y_test, y_pred)
    brier = brier_score_loss(y_test, y_pred_proba)

    print(f"\n--- Model Evaluation ---")
    print(f"AUC-ROC:     {auc_roc:.4f}")
    print(f"Accuracy:    {acc:.4f}")
    print(f"Brier Score: {brier:.4f} (lower is better, <0.25 = well calibrated)")
    print(f"\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=["Not Solved", "Solved"]))

    # Feature importance (coefficients)
    print(f"\n--- Feature Coefficients ---")
    for feat, coef in zip(FEATURE_COLS, model.coef_[0]):
        print(f"  {feat:30s} : {coef:+.4f}")
    print(f"  {'intercept':30s} : {model.intercept_[0]:+.4f}")

    # Calibration check — bin predictions and compare to actual solve rates
    print(f"\n--- Calibration Check ---")
    bins = np.linspace(0, 1, 11)
    bin_indices = np.digitize(y_pred_proba, bins) - 1
    for i in range(len(bins) - 1):
        mask = bin_indices == i
        if mask.sum() == 0:
            continue
        pred_mean = y_pred_proba[mask].mean()
        actual_mean = y_test[mask].mean()
        print(f"  Bin [{bins[i]:.1f}-{bins[i+1]:.1f}]: n={mask.sum():5d}, pred={pred_mean:.3f}, actual={actual_mean:.3f}, gap={abs(pred_mean - actual_mean):.3f}")

    return model, scaler, auc_roc


def save_model(model, scaler):
    os.makedirs(MODEL_DIR, exist_ok=True)
    model_path = os.path.join(MODEL_DIR, "p_solve_model.joblib")
    scaler_path = os.path.join(MODEL_DIR, "scaler.joblib")
    joblib.dump(model, model_path)
    joblib.dump(scaler, scaler_path)
    print(f"\nModel saved to {model_path}")
    print(f"Scaler saved to {scaler_path}")


def main():
    df = load_data()
    model, scaler, auc_roc = train_model(df)

    if auc_roc < 0.60:
        print(f"\nWARNING: AUC-ROC ({auc_roc:.4f}) is low. Model may need better features.")
    else:
        print(f"\nModel quality looks good (AUC-ROC={auc_roc:.4f}).")

    save_model(model, scaler)
    print("Done!")


if __name__ == "__main__":
    main()
